{
 "title": "nginx logs metrics",
 "time": { "from": "2024-06-19T18:48:22.000Z", "to": "2024-06-26T17:24:22.000Z" },
 "templating": {
  "list": [
   { "name": "query_key", "label": "query_key", "query": "session_id" },
   { "name": "query_value", "label": "query_value", "query": "ghi789" }
  ]
 },
 "panels": [
  { "title": "Errors and Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Responsed Time Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT date(`Timestamp`) as `day`,COUNT(`StatusCode`) as total_responses\r\nFROM xlogs\r\nWHERE StatusCode = 200\r\ngroup by `day`\r\norder by `day`;"
    }
   ]
  },
  {
   "title": "Error Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT date(`Timestamp`) as `date`, SUM(CASE WHEN StatusCode != 200 THEN 1 ELSE 0 END) / COUNT(*) AS error_rate\r\nFROM xlogs\r\nGROUP BY `date`;\r\n"
    }
   ]
  },
  {
   "title": "Top 15 Errored URL",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT URL, COUNT(*) AS errors\r\nFROM xlogs\r\nWHERE StatusCode != 200\r\ngroup by URL\r\nORDER BY errors desc\r\nLIMIT 15;\r\n"
    }
   ]
  },
  { "gridPos": { "h": 16, "w": 14, "x": 10, "y": 9 } },
  { "title": "Loads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Hourly Request Counts",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT HOUR(`Timestamp`) AS `hour`, COUNT(*) AS request_count\r\nFROM xlogs\r\nGROUP BY `hour`\r\norder by `hour`;\r\n"
    }
   ]
  },
  {
   "title": "Percentage of accessed parts",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT SUBSTRING_INDEX(URL, '?', 1) AS file_name, COUNT(*) AS hits\r\nFROM xlogs\r\nGROUP BY file_name\r\nORDER BY hits DESC;"
    }
   ]
  },
  {
   "title": "Traffic Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT `Timestamp`, SUM(ResponseSize) AS total_traffic\r\nFROM xlogs\r\nWHERE ResponseSize IS NOT NULL\r\nGROUP BY `Timestamp`\r\nORDER BY `Timestamp`;\r\n"
    }
   ]
  },
  {
   "title": "Average Response size by Hour",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT HOUR(`Timestamp`) AS hour, AVG(ResponseSize) AS avg_response_size\r\nFROM xlogs\r\nWHERE StatusCode = 200\r\nGROUP BY hour\r\norder by hour;\r\n"
    }
   ]
  },
  { "title": "Tops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Top 10 IP Addresses by Hits",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT IPAddress, COUNT(*) AS hits\r\nFROM xlogs\r\nWHERE IPAddress IS NOT NULL\r\nGROUP BY IPAddress\r\nORDER BY hits DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 URLs by Hits",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT URL, COUNT(*) AS hits\r\nFROM xlogs\r\nGROUP BY URL\r\nORDER BY hits DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  { "title": "special interactive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Hits of { $query_key : $query_value }",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 77 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT JSON_UNQUOTE(JSON_EXTRACT(QueryParams, '$.$query_key')) AS query_key, COUNT(*) AS hits\r\nFROM xlogs \r\nGROUP BY query_key \r\nhaving query_key = \"$query_value\"\r\nORDER BY hits DESC;\r\n"
    }
   ]
  }
 ]
}